database:
  url: "postgres://user:password@localhost:5432/scraperdb?sslmode=disable"

worker:
  type: 1
  maxRecipes: 20
  timeout: 30
  maxRetries: 3
  retryInterval: 5
  concurrency: 5
  rps: 10 # Ограничение запросов в секунду